# Generated by Django 3.2.6 on 2021-08-28 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=127)),
                ('description', models.TextField(default='', max_length=1027)),
                ('dead_line', models.DateTimeField()),
                ('status', models.CharField(choices=[('start', 'Start'), ('in_process', 'In process'), ('is_finished', 'Is finished')], default='Start', max_length=127)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
